import React from 'react';
import {Composition} from 'remotion';

// ⚠️  This file is auto-generated by the Remotion Studio server.
//     Do NOT edit manually — it is overwritten whenever you upload,
//     save, or delete a composition via the dashboard.
//
//     Each .tsx file in project_mnts/uploaded_tsx/ becomes one <Composition>.
//     Composition metadata (duration, fps, size) is read from the
//     @remotion comment on the first line of each file, e.g.:
//       // @remotion durationInFrames=900 fps=30 width=1920 height=1080

export const RemotionRoot: React.FC = () => {
  return (
    <>
      {/* Compositions are registered here by the server */}
    </>
  );
};
